
get http://localhost:8000/api/v1/properties/user/1/
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MTE3NTU2LCJpYXQiOjE3NzM5NDExNTYsImp0aSI6IjcxOWY5OGYxMGIzYTRjMzQ4NGQyMGU2ZjNlOGEyYjMxIiwidXNlcl9pZCI6IjMifQ.jpRpk8oTBWY6qhE8TbMHrdoy5IDPJeVUhhOhsSFKhgg

#  {
#           "location": {
#             "city": "Bahirdar",
#             "village": "Atse Tewodros",
#             "region": "amhara",
#             "latitude": "11.564600",
#             "longitude": "28.545000"
#           },
         
#           "title": "House for selling",
#           "description": "500 sqm house located in amhara region bahirdar city",
#           "area_sqm": 350,
#           "year_built": 2000,
#           "price": "3000.00",
#           "maintenance_fee": null,
#           "listing_type": "rent",
#           "is_active": true,
#           "is_available": false,
#           "is_featured": false,
#           "phone_contact": "0946472687",
#           "category": 1,
#           "owner": 2
#         }


#  {
# "name":"room",
# "description":"Room category description"
# }




#  {
# "name":"room",
# "description":"Room category description"
# }




# POST http://localhost:8000/api/v1/users/login/
# Content-Type:application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0MTE3MTk4LCJpYXQiOjE3NzM5NDA3OTgsImp0aSI6IjUyNTliNjYyNGY3NTRiOGM5YTkwNzQ3NjIwMDU1OGI1IiwidXNlcl9pZCI6IjEifQ.w0ZQU4BShHZOMShc9M5lD4ffaXpp8BaIDlTk68WdJyQ


# {
# "email":"yikeber@gmail.com",
# "password":"yike1234",
# "phone":"0947482444",
# "role":"OWNER",
# "name":"yikeber"
# }

# {
#     "email":"yikeber@gmail.com",
#     "password":"yike1234"
# }




# {
# "old_password":"yike1234",
# "new_password":"yike5678"
# }




# {
# "email":"yikeber50@gmail.com",
# "password":"yike1234",
# "phone":"0947488444",
# "role":"RENTER",
# "name":"yikeber"
# }



























