# Generated by Django 5.2.12 on 2026-03-19 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='total_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='used_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credit',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit', to=settings.AUTH_USER_MODEL),
        ),
    ]
