# Generated by Django 5.2.12 on 2026-03-19 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_alter_category_options_alter_category_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='City or Town name', max_length=100)),
                ('village', models.CharField(blank=True, help_text='Village or neighborhood name within city (optional)', max_length=100)),
                ('region', models.CharField(choices=[('addis_ababa', 'Addis Ababa'), ('oromia', 'Oromia'), ('amhara', 'Amhara'), ('snnpr', 'Southern Nations, Nationalities, and Peoples Region'), ('tigray', 'Tigray'), ('afar', 'Afar'), ('somali', 'Somali'), ('benishangul', 'Benishangul-Gumuz'), ('gambella', 'Gambella'), ('harari', 'Harari'), ('sidama', 'Sidama'), ('south_west', 'South West Ethiopia Peoples')], max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'ordering': ['city', 'village'],
                'unique_together': {('city', 'village', 'region')},
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('area_sqm', models.PositiveIntegerField(help_text='Area in square meters')),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in ETB', max_digits=15)),
                ('maintenance_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly fee in ETB', max_digits=12, null=True)),
                ('listing_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('phone_contact', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='categories.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
