# Generated by Django 5.2.12 on 2026-03-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['created_at'], 'verbose_name_plural': ['Properties']},
        ),
        migrations.AlterField(
            model_name='location',
            name='village',
            field=models.CharField(blank=True, help_text='Village or neighborhood name within', max_length=100),
        ),
    ]
